### ISSUE TITLE
Add in oAuth

### ISSUE THREAD

**Issue by rossdargan** [muyiwaolu/monzo-python#6]
Would you object to me adding in the Auth client from here: https://github.com/rossdargan/home-assistant/blob/1d4da009d5db327737db2199e9cf5086a91187ad/homeassistant/components/sensor/monzo.py#L90 to the library. 

If not I'm happy to create a fork with it added, but it might be useful to others!

**Comment by muyiwaolu** [comment]
Hey, just saw this. I would be happy to review a PR! :)
